name: SimpleSurvival
version: '1.0'
main: org.molfordan.simpleSurvival.Main
api-version: '1.21'
commands:
  setlocation:
    usage: /setlocation [locationName]
    description: set location
    aliases: [sl, setloc]
  location:
    usage: /location [locationName]
    description: location list
    aliases: [loc, l]
  seelocation:
    usage: /seelocation [target] [locationName]
    description: location list and name
    aliases: [seeloc, ssl, whereloc]
  deletelocation:
    usage: /deletelocation [locationName]
    description: delete location
    aliases: [delloc, del]
  simplesurvivalplugin:
    usage: /<command>
    description: yes
    aliases: [ssp]
  afk:
    usage: /afk
    description: afk
  tel:
    usage: /tel
    description: teleport
    aliases: [teleport, tel, tpp]
  deleteplayerlocation:
    usage: /deleteplayerlocation [<playerName>] [<locatioName>]
    description: delete player's location
    aliases: [dpl, delpl]
  setplayerlocation:
    usage: /spl  [<playerName>] [<locationName>] [x] [y] [z]
    description: create player's location
    aliases: [spl, setpl]
  nick:
    usage: /nick [name]
    description: nickname yourself
  ping:
    usage: /ping
    description: check some ping
  test:
    usage: /test
    description: test
  playerlevel:
    usage: /playerlevel [name]
    description: see player's level
    aliases: [plevel, pexp, seexp]
  mail:
    usage: /mail [name] [messages]
    description: mailing someone
  readmail:
    usage: /readmail
    description: see your mail
    aliases: [rm]
  message:
    usage: /message <player> <message>
    description: message a player
    aliases: [m]
  reply:
    usage: /reply <message>
    description: [r]
